### ISSUE TITLE
ch08 : (item=syncdb) => {"cmd": "python manage.py syncdb --noinput", "failed": true, "i

### ISSUE THREAD

**Issue by shamimgeek** [lorin/ansiblebook#9]
```
TASK: [sync the database, apply migrations, collect static content] *********** 
failed: [web] => (item=syncdb) => {"cmd": "python manage.py syncdb --noinput", "failed": true, "item": "syncdb", "path": "/home/vagrant/mezzanine-example/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", "state": "absent", "syspath": ["/home/vagrant/.ansible/tmp/ansible-tmp-1453320377.52-217648168657076", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages"]}
msg: 
:stderr: Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/compressor/conf.py", line 5, in <module>
    from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils

failed: [web] => (item=migrate) => {"cmd": "python manage.py migrate --noinput", "failed": true, "item": "migrate", "path": "/home/vagrant/mezzanine-example/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", "state": "absent", "syspath": ["/home/vagrant/.ansible/tmp/ansible-tmp-1453320378.13-242683810168516", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages"]}
msg: 
:stderr: Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/compressor/conf.py", line 5, in <module>
    from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils

failed: [web] => (item=collectstatic) => {"cmd": "python manage.py collectstatic --noinput", "failed": true, "item": "collectstatic", "path": "/home/vagrant/mezzanine-example/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", "state": "absent", "syspath": ["/home/vagrant/.ansible/tmp/ansible-tmp-1453320378.75-239046207808436", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages"]}
```

**Comment by ghost** [comment]
you should fork the example to your github account, and then edit the requirements.txt as follows: 

vagrant@vagrant-ubuntu-trusty-64:~/mezzanine-example$ bin/pip freeze
Django==1.6.11
Mezzanine==3.1.10
Pillow==2.9.0
South==1.0.2
argparse==1.2.1
beautifulsoup4==4.1.3
bleach==1.4.2
django-appconf==1.0.1
django-compressor==1.5
filebrowser-safe==0.4.0
future==0.9.0
grappelli-safe==0.4.1
gunicorn==19.3.0
html5lib==0.9999999
oauthlib==1.0.3
psycopg2==2.6.1
python-memcached==1.57
pytz==2015.6
requests==2.7.0
requests-oauthlib==0.5.0
setproctitle==1.1.9
six==1.9.0
tzlocal==1.0
wsgiref==0.1.2 

Then, save and push it to your github again, then it should be fine
